# Generated by Django 5.2.9 on 2025-12-25 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Follow',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
        ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
      ],
      options={
        'indexes': [models.Index(fields=['follower'], name='users_follo_followe_3a2483_idx'), models.Index(fields=['following'], name='users_follo_followi_e01def_idx')],
        'unique_together': {('follower', 'following')},
      },
    ),
  ]
