# Generated by Django 5.2.9 on 2025-12-24 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Article',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('title', models.CharField(db_index=True, max_length=255, unique=True)),
        ('slug', models.SlugField(max_length=100, unique=True)),
        ('content', models.TextField()),
        ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to=settings.AUTH_USER_MODEL)),
      ],
      options={
        'ordering': ['-created_at'],
      },
    ),
    migrations.CreateModel(
      name='Comment',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('content', models.TextField()),
        ('slug', models.SlugField(max_length=100, unique=True)),
        ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
        ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to=settings.AUTH_USER_MODEL)),
      ],
      options={
          'ordering': ['-created_at'],
      },
    ),
    migrations.CreateModel(
      name='Tag',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(db_index=True, max_length=100, unique=True)),
        ('slug', models.SlugField(max_length=100, unique=True)),
        ('description', models.TextField(blank=True, null=True)),
      ],
      options={
        'ordering': ['name'],
        'indexes': [models.Index(fields=['slug'], name='articles_ta_slug_7a73a7_idx'), models.Index(fields=['name'], name='articles_ta_name_917d3f_idx')],
      },
    ),
    migrations.AddField(
      model_name='article',
      name='tags',
      field=models.ManyToManyField(blank=True, related_name='articles', to='articles.tag'),
    ),
    migrations.AddIndex(
      model_name='article',
      index=models.Index(fields=['author'], name='articles_ar_author__8895b2_idx'),
    ),
    migrations.AddIndex(
      model_name='article',
      index=models.Index(fields=['title'], name='articles_ar_title_ee81af_idx'),
    ),
    migrations.AddIndex(
      model_name='article',
      index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
    ),
  ]
