# Generated by Django 5.2.9 on 2025-12-24 01:08

from django.db import migrations, models

class Migration(migrations.Migration):
  dependencies = [
    ('articles', '0001_initial'),
    ('tags', '0001_initial'),
  ]

  operations = [
    migrations.DeleteModel(
      name='Tag',
    ),
    migrations.AlterField(
      model_name='article',
      name='tags',
      field=models.ManyToManyField(blank=True, related_name='articles', to='tags.tag'),
    ),
  ]
