# Generated by Django 5.2.9 on 2025-12-30 08:05

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
  dependencies = [
    ('articles', '0003_article_favorited_by'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddField(
      model_name='article',
      name='liked_by',
      field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
    ),
  ]
