# Generated by Django 5.2.9 on 2025-12-24 01:08

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Tag',
      fields=[
        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ('name', models.CharField(db_index=True, max_length=100, unique=True)),
        ('slug', models.SlugField(max_length=100, unique=True)),
        ('description', models.TextField(blank=True, null=True)),
      ],
      options={
        'ordering': ['name'],
        'indexes': [models.Index(fields=['slug'], name='tags_tag_slug_dcb0c2_idx'), models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx')],
      },
    ),
  ]
