# Generated by Django 5.2.9 on 2025-12-16 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

  initial = True

  dependencies = [
  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
  migrations.CreateModel(
  name='Article',
  fields=[
      ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
      ('updated_at', models.DateTimeField(auto_now=True)),
      ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
      ('title', models.CharField(max_length=300)),
      ('content', models.TextField()),
      ('slug', models.SlugField(max_length=300, unique=True)),
      ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
  ],
  options={
      'ordering': ['-created_at'],
  },
  ),
  migrations.CreateModel(
  name='Comment',
  fields=[
      ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
      ('updated_at', models.DateTimeField(auto_now=True)),
      ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
      ('content', models.TextField()),
      ('slug', models.SlugField(max_length=100, unique=True)),
      ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
      ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
  ],
  options={
      'ordering': ['-created_at'],
  },
  ),
  migrations.CreateModel(
  name='Tag',
  fields=[
      ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
      ('updated_at', models.DateTimeField(auto_now=True)),
      ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
      ('name', models.CharField(db_index=True, max_length=100, unique=True)),
      ('slug', models.SlugField(max_length=100, unique=True)),
      ('description', models.TextField(blank=True, null=True)),
  ],
  options={
      'ordering': ['name'],
      'indexes': [models.Index(fields=['slug'], name='blog_tag_slug_915fc6_idx'), models.Index(fields=['name'], name='blog_tag_name_43b6ed_idx')],
  },
  ),
  migrations.AddField(
  model_name='article',
  name='tags',
  field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag'),
  ),
  migrations.CreateModel(
  name='UserProfile',
  fields=[
      ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
      ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
      ('updated_at', models.DateTimeField(auto_now=True)),
      ('bio', models.TextField(blank=True, null=True)),
      ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
      ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
  ],
  options={
      'verbose_name': 'User Profile',
      'verbose_name_plural': 'User Profiles',
  },
  ),
  ]
